/* One-off: vendor self-hosted woff2 fonts (brand.md — "No external font
   CDNs"). Downloads the latin subset of each family/weight from Google's
   static host into public/fonts/, then writes src/styles/fonts.css with
   @font-face rules that point at the local files. Re-runnable.

   Run with: node scripts/fetch-fonts.mjs */

import { writeFileSync, mkdirSync } from "fs";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) " +
  "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/* Families + weights actually used (tokens.css / HANDOFF typography). */
const FAMILIES = [
  { css: "Space+Grotesk:wght@500;600;700", file: "space-grotesk" },
  { css: "Inter:wght@400", file: "inter" },
  { css: "IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400", file: "ibm-plex-mono" },
];

mkdirSync("public/fonts", { recursive: true });

const faces = [];

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) =>
    r.text(),
  );

  // Each "/* latin */" comment precedes one @font-face block for that weight.
  const re = /\/\* latin \*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  let found = 0;
  while ((m = re.exec(css))) {
    const block = m[1];
    const family = /font-family:\s*'([^']+)'/.exec(block)[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)[1];
    const style = /font-style:\s*(\w+)/.exec(block)[1];
    const src = /src:\s*url\((https:[^)]+)\)/.exec(block)[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)[1].trim();

    const name =
      `${fam.file}-${weight}` + (style === "italic" ? "-italic" : "");
    const buf = Buffer.from(
      await fetch(src, { headers: { "User-Agent": UA } }).then((r) =>
        r.arrayBuffer(),
      ),
    );
    writeFileSync(`public/fonts/${name}.woff2`, buf);
    found++;

    faces.push(
      `@font-face {\n` +
        `  font-family: "${family}";\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url("/fonts/${name}.woff2") format("woff2");\n` +
        `  unicode-range: ${range};\n` +
        `}`,
    );
    console.log(`  ${name}.woff2  (${(buf.length / 1024).toFixed(1)} KB)`);
  }
  if (!found) throw new Error(`no latin subset found for ${fam.css}`);
}

const header =
  "/* Self-hosted fonts — latin subset, generated by scripts/fetch-fonts.mjs.\n" +
  "   brand.md: Space Grotesk (headlines) / Inter (body) / IBM Plex Mono\n" +
  "   (labels). No external font CDNs — files live in public/fonts/. */\n\n";
writeFileSync("src/styles/fonts.css", header + faces.join("\n\n") + "\n");

console.log(`\n✓ ${faces.length} faces -> public/fonts/, src/styles/fonts.css`);
